Set-StrictMode -Version Latest

# NOTE: -Force omitted DELIBERATELY. With -Force, this re-import cascades through
# Tiny11.Actions.psm1 -> Actions.Registry.psm1 -> Tiny11.Hives.psm1 (which has no
# -Global flag in Actions.Registry's import), causing Hives to be reloaded at
# non-global scope. That replaces the global Hives instance that Tiny11.Worker.psm1
# established at its top-level import, and Mount-Tiny11AllHives becomes invisible
# to the Worker pipeline at runtime (verified via P1c smoke).
Import-Module (Join-Path $PSScriptRoot 'Tiny11.Actions.psm1') -Global -DisableNameChecking

# Module-scope constants populated by tasks 8-9.
$script:headerBlock = @'
# tiny11-cleanup.ps1 -- Re-applies the catalog-driven removal/tweak recipe on every boot,
# daily at 03:00, and on every Windows Update event. Generated by
# New-Tiny11PostBootCleanupScript (src/Tiny11.PostBoot.psm1).
#
# Idempotent: when state is already correct, every check is a fast read-and-skip.
# Logs each check + action (with before/after on corrections) to
# %SystemDrive%\Windows\Logs\tiny11-cleanup.log. Rotates to .log.1 when the active
# log reaches 5000 lines.

$ErrorActionPreference = 'Continue'
$logPath       = "$env:SystemDrive\Windows\Logs\tiny11-cleanup.log"
$logPathBackup = "$env:SystemDrive\Windows\Logs\tiny11-cleanup.log.1"
$logDir        = Split-Path -Parent $logPath
if (-not (Test-Path -LiteralPath $logDir)) { New-Item -ItemType Directory -Path $logDir -Force | Out-Null }

if (Test-Path -LiteralPath $logPath) {
    try {
        $lineCount = ([System.IO.File]::ReadAllLines($logPath)).Length
        if ($lineCount -ge 5000) {
            if (Test-Path -LiteralPath $logPathBackup) {
                Remove-Item -LiteralPath $logPathBackup -Force -ErrorAction SilentlyContinue
            }
            Move-Item -LiteralPath $logPath -Destination $logPathBackup -Force -ErrorAction SilentlyContinue
        }
    } catch {
        # Rotation failure shouldn't break enforcement; swallow.
    }
}

function Write-CleanupLog {
    param([string]$Message)
    $line = '[{0}] {1}' -f (Get-Date -Format 'yyyy-MM-dd HH:mm:ss'), $Message
    Add-Content -LiteralPath $logPath -Value $line -Encoding UTF8 -ErrorAction SilentlyContinue
}

Write-CleanupLog '==== tiny11-cleanup triggered ===='

# Mount HKU: PSDrive -- SYSTEM-context PS 5.1 sessions (which is what the
# scheduled task gets) don't auto-mount it, and every Set-RegistryValueForAllUsers
# call below depends on it. Idempotent: skip if already present.
if (-not (Get-PSDrive -Name HKU -ErrorAction SilentlyContinue)) {
    try {
        New-PSDrive -Name HKU -PSProvider Registry -Root HKEY_USERS -Scope Global -ErrorAction Stop | Out-Null
        Write-CleanupLog "  HKU: PSDrive mounted"
    } catch {
        Write-CleanupLog "  HKU: PSDrive mount FAILED: $($_.Exception.Message)"
    }
}

# Load the default-user registry hive (C:\Users\Default\NTUSER.DAT) into a
# transient HKU subkey so writes from Set-RegistryValueForAllUsers and
# Remove-RegistryKeyForAllUsers propagate to user profiles created AFTER this
# run. Replaces the legacy .DEFAULT target -- .DEFAULT actually backs the
# LOCAL_SERVICE / NETWORK_SERVICE hive, NOT the new-user-profile template.
$defaultHivePath = "$env:SystemDrive\Users\Default\NTUSER.DAT"
$defaultHiveOwnedByThisRun = $false
if (Test-Path -LiteralPath $defaultHivePath) {
    if (-not (Test-Path -LiteralPath 'HKU:\tiny11_default')) {
        & reg.exe load 'HKU\tiny11_default' $defaultHivePath 2>&1 | Out-Null
        if ($LASTEXITCODE -eq 0) {
            $defaultHiveOwnedByThisRun = $true
            Write-CleanupLog '  default-user hive loaded into HKU:\tiny11_default'
        } else {
            Write-CleanupLog "  default-user hive load FAILED (reg.exe rc=$LASTEXITCODE) -- new profiles will NOT inherit changes from this run"
        }
    } else {
        Write-CleanupLog '  default-user hive HKU:\tiny11_default already mounted; reusing (will NOT unload at end)'
    }
} else {
    Write-CleanupLog "  default-user hive file not found at $defaultHivePath -- new profiles will NOT inherit changes"
}
'@

$script:helpersBlock = @'
function Set-RegistryValue {
    param([string]$KeyPath, [string]$Name, [string]$Type, $Value)
    if (-not (Test-Path -LiteralPath $KeyPath)) {
        try { New-Item -Path $KeyPath -Force -ErrorAction Stop | Out-Null }
        catch { Write-CleanupLog "  $KeyPath key-create FAILED: $($_.Exception.Message)"; return }
    }
    $current = (Get-ItemProperty -LiteralPath $KeyPath -Name $Name -ErrorAction SilentlyContinue).$Name
    if ($null -ne $current -and $current -eq $Value) {
        Write-CleanupLog "  $KeyPath!$Name=$Value already"
        return
    }
    try {
        Set-ItemProperty -LiteralPath $KeyPath -Name $Name -Value $Value -Type $Type -ErrorAction Stop
        Write-CleanupLog "  $KeyPath!$Name CORRECTED: '$current' -> '$Value'"
    } catch {
        Write-CleanupLog "  $KeyPath!$Name correction FAILED: $($_.Exception.Message)"
    }
}

function Set-RegistryValueForAllUsers {
    param([string]$RelativeKeyPath, [string]$Name, [string]$Type, $Value)
    # NB: Select-Object -ExpandProperty (not (...).PSChildName). The trailing
    # property accessor on an empty pipeline returns $null, which @() then wraps
    # as a single-null-element array -- iterating it yields one bogus
    # HKU:\\<path> write with sid="". -ExpandProperty preserves empty-when-empty.
    $sids = @(Get-ChildItem 'HKU:\' -ErrorAction SilentlyContinue |
              Where-Object { $_.PSChildName -match '^S-1-5-21-\d+-\d+-\d+-\d+$' } |
              Select-Object -ExpandProperty PSChildName)
    # Append the loaded default-user hive (so new profiles inherit) instead of
    # .DEFAULT (which is the LOCAL_SERVICE/NETWORK_SERVICE hive, not the
    # new-user template). The hive is loaded once in the header.
    if (Test-Path -LiteralPath 'HKU:\tiny11_default') { $sids += 'tiny11_default' }
    foreach ($sid in $sids) {
        Set-RegistryValue -KeyPath "HKU:\$sid\$RelativeKeyPath" -Name $Name -Type $Type -Value $Value
    }
}

function Remove-RegistryKey {
    param([string]$KeyPath)
    if (-not (Test-Path -LiteralPath $KeyPath)) {
        Write-CleanupLog "  $KeyPath absent (no-op)"
        return
    }
    try {
        Remove-Item -LiteralPath $KeyPath -Recurse -Force -ErrorAction Stop
        Write-CleanupLog "  $KeyPath REMOVED"
    } catch {
        Write-CleanupLog "  $KeyPath remove FAILED: $($_.Exception.Message)"
    }
}

function Remove-RegistryKeyForAllUsers {
    param([string]$RelativeKeyPath)
    # See Set-RegistryValueForAllUsers for why -ExpandProperty (not .PSChildName).
    $sids = @(Get-ChildItem 'HKU:\' -ErrorAction SilentlyContinue |
              Where-Object { $_.PSChildName -match '^S-1-5-21-\d+-\d+-\d+-\d+$' } |
              Select-Object -ExpandProperty PSChildName)
    if (Test-Path -LiteralPath 'HKU:\tiny11_default') { $sids += 'tiny11_default' }
    foreach ($sid in $sids) {
        Remove-RegistryKey -KeyPath "HKU:\$sid\$RelativeKeyPath"
    }
}

function Remove-PathIfPresent {
    param([string]$Path, [bool]$Recurse)
    if (-not (Test-Path -LiteralPath $Path)) {
        Write-CleanupLog "  $Path absent (no-op)"
        return
    }
    try {
        if ($Recurse) { Remove-Item -LiteralPath $Path -Recurse -Force -ErrorAction Stop }
        else          { Remove-Item -LiteralPath $Path -Force -ErrorAction Stop }
        Write-CleanupLog "  $Path REMOVED"
    } catch {
        Write-CleanupLog "  $Path remove FAILED: $($_.Exception.Message)"
    }
}

function Remove-PathWithOwnership {
    param([string]$Path, [bool]$Recurse)
    if (-not (Test-Path -LiteralPath $Path)) {
        Write-CleanupLog "  $Path absent (no-op)"
        return
    }
    $adminSid = New-Object System.Security.Principal.SecurityIdentifier 'S-1-5-32-544'
    $admin    = $adminSid.Translate([System.Security.Principal.NTAccount]).Value
    $takeownArgs = @('/f', $Path)
    if ($Recurse) { $takeownArgs += '/r','/d','Y' }
    try {
        & takeown.exe @takeownArgs | Out-Null
        & icacls.exe $Path '/grant' "$admin`:(F)" '/T' '/C' | Out-Null
        if ($Recurse) { Remove-Item -LiteralPath $Path -Recurse -Force -ErrorAction Stop }
        else          { Remove-Item -LiteralPath $Path -Force -ErrorAction Stop }
        Write-CleanupLog "  $Path REMOVED (with takeown)"
    } catch {
        Write-CleanupLog "  $Path takeown-remove FAILED: $($_.Exception.Message)"
    }
}

function Remove-AppxByPackagePrefix {
    param([string]$Prefix)
    # B8: explicit Appx module load -- defensive against debloated images and
    # SYSTEM-context PS 5.1 sessions (which is what the scheduled task gets)
    # where module auto-discovery may not find Appx and the cmdlets below would
    # throw "not recognized". Idempotent: subsequent calls are no-ops.
    Import-Module Appx -ErrorAction SilentlyContinue
    $provMatches = @(Get-AppxProvisionedPackage -Online -ErrorAction SilentlyContinue |
                    Where-Object DisplayName -like "$Prefix*")
    if ($provMatches.Count -eq 0) {
        Write-CleanupLog "  appx provisioned '$Prefix*' absent (no-op)"
    } else {
        foreach ($p in $provMatches) {
            try {
                Remove-AppxProvisionedPackage -Online -PackageName $p.PackageName -ErrorAction Stop | Out-Null
                Write-CleanupLog "  appx provisioned $($p.PackageName) REMOVED"
            } catch {
                Write-CleanupLog "  appx provisioned $($p.PackageName) remove FAILED: $($_.Exception.Message)"
            }
        }
    }
    $userMatches = @(Get-AppxPackage -AllUsers -Name "$Prefix*" -ErrorAction SilentlyContinue)
    if ($userMatches.Count -eq 0) {
        Write-CleanupLog "  appx per-user '$Prefix*' absent (no-op)"
    } else {
        foreach ($p in $userMatches) {
            try {
                Remove-AppxPackage -AllUsers -Package $p.PackageFullName -ErrorAction Stop
                Write-CleanupLog "  appx per-user $($p.PackageFullName) REMOVED"
            } catch {
                Write-CleanupLog "  appx per-user $($p.PackageFullName) remove FAILED: $($_.Exception.Message)"
            }
        }
    }
}
'@

$script:footerBlock = @'
# Unload the default-user hive if WE loaded it (don't unload one we found
# already mounted from a prior unclean run -- the owner cleans up). Force a
# GC + brief pause first because Set-ItemProperty / Get-ItemProperty leave
# handles open momentarily; reg.exe unload would otherwise return non-zero
# with the hive still mounted.
if ($defaultHiveOwnedByThisRun) {
    [GC]::Collect(); [GC]::WaitForPendingFinalizers(); Start-Sleep -Milliseconds 200
    & reg.exe unload 'HKU\tiny11_default' 2>&1 | Out-Null
    if ($LASTEXITCODE -eq 0) {
        Write-CleanupLog '  default-user hive unloaded'
    } else {
        Write-CleanupLog "  default-user hive unload FAILED (reg.exe rc=$LASTEXITCODE) -- handle may still be open; the next run will reuse the existing mount"
    }
}

Write-CleanupLog '==== tiny11-cleanup done ===='
'@

function Format-PSNamedParams {
    [CmdletBinding()]
    param([Parameter(Mandatory)][System.Collections.IDictionary] $Arguments)
    $parts = foreach ($entry in $Arguments.GetEnumerator()) {
        $value = $entry.Value
        $rendered = if ($value -is [bool]) {
            if ($value) { '$true' } else { '$false' }
        } elseif ($value -is [int] -or $value -is [long]) {
            "$value"
        } elseif ($value -is [byte[]]) {
            $hex = ($value | ForEach-Object { '0x{0:X2}' -f $_ }) -join ','
            "([byte[]]($hex))"
        } elseif ($value -is [array]) {
            $quoted = ($value | ForEach-Object { "'" + ([string]$_ -replace "'", "''") + "'" }) -join ','
            "@($quoted)"
        } elseif (([string]$value) -match '\$env:') {
            # Contains an env-var reference -- emit DOUBLE-quoted so PowerShell
            # expands it at runtime on the target machine. Single quotes would
            # suppress expansion and leave a literal '$env:...' path that
            # Test-Path can never resolve, silently no-op'ing the action.
            $s = [string]$value
            $escaped = $s -replace '`','``' -replace '"','`"'
            '"' + $escaped + '"'
        } else {
            $s = [string]$value
            "'" + ($s -replace "'", "''") + "'"
        }
        "-$($entry.Key) $rendered"
    }
    $parts -join ' '
}

function New-Tiny11PostBootCleanupScript {
    [CmdletBinding()]
    param(
        [Parameter(Mandatory)]            $Catalog,
        [Parameter(Mandatory)][hashtable] $ResolvedSelections
    )
    $sb = [System.Text.StringBuilder]::new()
    [void]$sb.AppendLine($script:headerBlock)
    [void]$sb.AppendLine('')
    [void]$sb.AppendLine($script:helpersBlock)
    [void]$sb.AppendLine('')

    foreach ($item in $Catalog.Items) {
        if (-not $ResolvedSelections.ContainsKey($item.id)) { continue }
        if ($ResolvedSelections[$item.id].EffectiveState -ne 'apply') { continue }

        [void]$sb.AppendLine("# --- Item: $($item.displayName) ($($item.id)) ---")
        foreach ($action in $item.actions) {
            $commands = @(Get-Tiny11ActionOnlineCommand -Action $action)
            foreach ($cmd in $commands) {
                [void]$sb.AppendLine("# $($cmd.Description)")
                $argsRendered = Format-PSNamedParams -Arguments $cmd.Args
                [void]$sb.AppendLine("$($cmd.Kind) $argsRendered")
            }
        }
        [void]$sb.AppendLine('')
    }

    [void]$sb.AppendLine($script:footerBlock)
    $sb.ToString()
}

function New-Tiny11PostBootTaskXml {
    [CmdletBinding()] param()
    @'
<?xml version="1.0" encoding="UTF-16"?>
<Task version="1.4" xmlns="http://schemas.microsoft.com/windows/2004/02/mit/task">
  <RegistrationInfo>
    <Date>2026-05-12T00:00:00</Date>
    <Author>tiny11options</Author>
    <Description>Re-applies catalog-driven offline removals after Windows Update restages inbox apps and resets settings. Idempotent fast no-op when state is already correct.</Description>
    <URI>\tiny11options\Post-Boot Cleanup</URI>
  </RegistrationInfo>
  <Triggers>
    <BootTrigger>
      <Enabled>true</Enabled>
      <Delay>PT10M</Delay>
    </BootTrigger>
    <CalendarTrigger>
      <StartBoundary>2026-01-01T03:00:00</StartBoundary>
      <Enabled>true</Enabled>
      <ScheduleByDay><DaysInterval>1</DaysInterval></ScheduleByDay>
    </CalendarTrigger>
    <EventTrigger>
      <Enabled>true</Enabled>
      <Subscription>&lt;QueryList&gt;&lt;Query Id="0" Path="Microsoft-Windows-WindowsUpdateClient/Operational"&gt;&lt;Select Path="Microsoft-Windows-WindowsUpdateClient/Operational"&gt;*[System[(EventID=19)]]&lt;/Select&gt;&lt;/Query&gt;&lt;/QueryList&gt;</Subscription>
    </EventTrigger>
  </Triggers>
  <Principals>
    <Principal id="Author">
      <UserId>S-1-5-18</UserId>
      <RunLevel>HighestAvailable</RunLevel>
    </Principal>
  </Principals>
  <Settings>
    <MultipleInstancesPolicy>IgnoreNew</MultipleInstancesPolicy>
    <DisallowStartIfOnBatteries>false</DisallowStartIfOnBatteries>
    <StopIfGoingOnBatteries>false</StopIfGoingOnBatteries>
    <AllowHardTerminate>true</AllowHardTerminate>
    <StartWhenAvailable>true</StartWhenAvailable>
    <RunOnlyIfNetworkAvailable>false</RunOnlyIfNetworkAvailable>
    <ExecutionTimeLimit>PT30M</ExecutionTimeLimit>
    <Priority>7</Priority>
  </Settings>
  <Actions Context="Author">
    <Exec>
      <Command>powershell.exe</Command>
      <Arguments>-NoProfile -ExecutionPolicy Bypass -WindowStyle Hidden -File "C:\Windows\Setup\Scripts\tiny11-cleanup.ps1"</Arguments>
    </Exec>
  </Actions>
</Task>
'@
}

function New-Tiny11PostBootSetupCompleteScript {
    [CmdletBinding()] param()
    @'
@echo off
:: tiny11options post-boot cleanup
:: Runs once at first boot via SetupComplete.cmd contract:
::   Registers the Post-Boot Cleanup scheduled task.

set TINY11_LOG=%SystemDrive%\Windows\Logs\tiny11-cleanup-setup.log
if not exist "%SystemDrive%\Windows\Logs" mkdir "%SystemDrive%\Windows\Logs" >nul 2>&1

echo [tiny11options] Registering Post-Boot Cleanup scheduled task at %date% %time% > "%TINY11_LOG%"
schtasks /create /xml "%SystemDrive%\Windows\Setup\Scripts\tiny11-cleanup.xml" /tn "tiny11options\Post-Boot Cleanup" /f >> "%TINY11_LOG%" 2>&1
echo [tiny11options] schtasks exited with %ERRORLEVEL% >> "%TINY11_LOG%"

echo [tiny11options] Running tiny11-cleanup.ps1 once immediately >> "%TINY11_LOG%"
powershell.exe -NoProfile -ExecutionPolicy Bypass -WindowStyle Hidden -File "%SystemDrive%\Windows\Setup\Scripts\tiny11-cleanup.ps1" >> "%TINY11_LOG%" 2>&1
echo [tiny11options] cleanup.ps1 exited with %ERRORLEVEL% >> "%TINY11_LOG%"

del /F /Q "%~f0"
'@
}

function Install-Tiny11PostBootCleanup {
    [CmdletBinding()]
    param(
        [Parameter(Mandatory)][string]    $MountDir,
        [Parameter(Mandatory)]            $Catalog,
        [Parameter(Mandatory)][hashtable] $ResolvedSelections,
        [bool]                            $Enabled = $true
    )
    if (-not $Enabled) { return }

    $scriptsDir = Join-Path $MountDir 'Windows\Setup\Scripts'
    if (-not (Test-Path -LiteralPath $scriptsDir)) {
        New-Item -ItemType Directory -Path $scriptsDir -Force | Out-Null
    }

    # 1. SetupComplete.cmd -- ASCII + CRLF
    $cmdContent     = New-Tiny11PostBootSetupCompleteScript
    $cmdContentCRLF = ($cmdContent -split "`r?`n") -join "`r`n"
    [System.IO.File]::WriteAllText(
        (Join-Path $scriptsDir 'SetupComplete.cmd'),
        $cmdContentCRLF,
        [System.Text.Encoding]::ASCII)

    # 2. tiny11-cleanup.ps1 -- UTF-8 + BOM
    $psContent = New-Tiny11PostBootCleanupScript -Catalog $Catalog -ResolvedSelections $ResolvedSelections
    [System.IO.File]::WriteAllText(
        (Join-Path $scriptsDir 'tiny11-cleanup.ps1'),
        $psContent,
        [System.Text.UTF8Encoding]::new($true))

    # 3. tiny11-cleanup.xml -- UTF-16 LE + BOM
    $xmlContent = New-Tiny11PostBootTaskXml
    [System.IO.File]::WriteAllText(
        (Join-Path $scriptsDir 'tiny11-cleanup.xml'),
        $xmlContent,
        [System.Text.Encoding]::Unicode)
}

Export-ModuleMember -Function `
    Format-PSNamedParams, `
    New-Tiny11PostBootCleanupScript, `
    New-Tiny11PostBootTaskXml, `
    New-Tiny11PostBootSetupCompleteScript, `
    Install-Tiny11PostBootCleanup
