Set-StrictMode -Version Latest

# Module-scope constants populated by tasks 8-9.
$script:headerBlock = @'
# tiny11-cleanup.ps1 -- Re-applies the catalog-driven removal/tweak recipe on every boot,
# daily at 03:00, and on every Windows Update event. Generated by
# New-Tiny11PostBootCleanupScript (src/Tiny11.PostBoot.psm1).
#
# Idempotent: when state is already correct, every check is a fast read-and-skip.
# Logs each check + action (with before/after on corrections) to
# %SystemDrive%\Windows\Logs\tiny11-cleanup.log. Rotates to .log.1 when the active
# log reaches 5000 lines.

$ErrorActionPreference = 'Continue'
$logPath       = "$env:SystemDrive\Windows\Logs\tiny11-cleanup.log"
$logPathBackup = "$env:SystemDrive\Windows\Logs\tiny11-cleanup.log.1"
$logDir        = Split-Path -Parent $logPath
if (-not (Test-Path -LiteralPath $logDir)) { New-Item -ItemType Directory -Path $logDir -Force | Out-Null }

if (Test-Path -LiteralPath $logPath) {
    try {
        $lineCount = ([System.IO.File]::ReadAllLines($logPath)).Length
        if ($lineCount -ge 5000) {
            if (Test-Path -LiteralPath $logPathBackup) {
                Remove-Item -LiteralPath $logPathBackup -Force -ErrorAction SilentlyContinue
            }
            Move-Item -LiteralPath $logPath -Destination $logPathBackup -Force -ErrorAction SilentlyContinue
        }
    } catch {
        # Rotation failure shouldn't break enforcement; swallow.
    }
}

function Write-CleanupLog {
    param([string]$Message)
    $line = '[{0}] {1}' -f (Get-Date -Format 'yyyy-MM-dd HH:mm:ss'), $Message
    Add-Content -LiteralPath $logPath -Value $line -Encoding UTF8 -ErrorAction SilentlyContinue
}

Write-CleanupLog '==== tiny11-cleanup triggered ===='
'@

$script:helpersBlock = ''
$script:footerBlock  = ''

function Format-PSNamedParams {
    [CmdletBinding()]
    param([Parameter(Mandatory)][System.Collections.IDictionary] $Arguments)
    $parts = foreach ($entry in $Arguments.GetEnumerator()) {
        $value = $entry.Value
        $rendered = if ($value -is [bool]) {
            if ($value) { '$true' } else { '$false' }
        } elseif ($value -is [int] -or $value -is [long]) {
            "$value"
        } elseif ($value -is [byte[]]) {
            $hex = ($value | ForEach-Object { '0x{0:X2}' -f $_ }) -join ','
            "([byte[]]($hex))"
        } elseif ($value -is [array]) {
            $quoted = ($value | ForEach-Object { "'" + ([string]$_ -replace "'", "''") + "'" }) -join ','
            "@($quoted)"
        } else {
            $s = [string]$value
            "'" + ($s -replace "'", "''") + "'"
        }
        "-$($entry.Key) $rendered"
    }
    $parts -join ' '
}

function New-Tiny11PostBootCleanupScript {
    [CmdletBinding()]
    param(
        [Parameter(Mandatory)]            $Catalog,
        [Parameter(Mandatory)][hashtable] $ResolvedSelections
    )
    throw 'New-Tiny11PostBootCleanupScript not yet implemented'
}

function New-Tiny11PostBootTaskXml {
    [CmdletBinding()] param()
    throw 'New-Tiny11PostBootTaskXml not yet implemented'
}

function New-Tiny11PostBootSetupCompleteScript {
    [CmdletBinding()] param()
    throw 'New-Tiny11PostBootSetupCompleteScript not yet implemented'
}

function Install-Tiny11PostBootCleanup {
    [CmdletBinding()]
    param(
        [Parameter(Mandatory)][string]    $MountDir,
        [Parameter(Mandatory)]            $Catalog,
        [Parameter(Mandatory)][hashtable] $ResolvedSelections,
        [bool]                            $Enabled = $true
    )
    throw 'Install-Tiny11PostBootCleanup not yet implemented'
}

Export-ModuleMember -Function `
    Format-PSNamedParams, `
    New-Tiny11PostBootCleanupScript, `
    New-Tiny11PostBootTaskXml, `
    New-Tiny11PostBootSetupCompleteScript, `
    Install-Tiny11PostBootCleanup
