Set-StrictMode -Version Latest

# Module-scope constants populated by tasks 8-9.
$script:headerBlock = @'
# tiny11-cleanup.ps1 -- Re-applies the catalog-driven removal/tweak recipe on every boot,
# daily at 03:00, and on every Windows Update event. Generated by
# New-Tiny11PostBootCleanupScript (src/Tiny11.PostBoot.psm1).
#
# Idempotent: when state is already correct, every check is a fast read-and-skip.
# Logs each check + action (with before/after on corrections) to
# %SystemDrive%\Windows\Logs\tiny11-cleanup.log. Rotates to .log.1 when the active
# log reaches 5000 lines.

$ErrorActionPreference = 'Continue'
$logPath       = "$env:SystemDrive\Windows\Logs\tiny11-cleanup.log"
$logPathBackup = "$env:SystemDrive\Windows\Logs\tiny11-cleanup.log.1"
$logDir        = Split-Path -Parent $logPath
if (-not (Test-Path -LiteralPath $logDir)) { New-Item -ItemType Directory -Path $logDir -Force | Out-Null }

if (Test-Path -LiteralPath $logPath) {
    try {
        $lineCount = ([System.IO.File]::ReadAllLines($logPath)).Length
        if ($lineCount -ge 5000) {
            if (Test-Path -LiteralPath $logPathBackup) {
                Remove-Item -LiteralPath $logPathBackup -Force -ErrorAction SilentlyContinue
            }
            Move-Item -LiteralPath $logPath -Destination $logPathBackup -Force -ErrorAction SilentlyContinue
        }
    } catch {
        # Rotation failure shouldn't break enforcement; swallow.
    }
}

function Write-CleanupLog {
    param([string]$Message)
    $line = '[{0}] {1}' -f (Get-Date -Format 'yyyy-MM-dd HH:mm:ss'), $Message
    Add-Content -LiteralPath $logPath -Value $line -Encoding UTF8 -ErrorAction SilentlyContinue
}

Write-CleanupLog '==== tiny11-cleanup triggered ===='
'@

$script:helpersBlock = @'
function Set-RegistryValue {
    param([string]$KeyPath, [string]$Name, [string]$Type, $Value)
    if (-not (Test-Path -LiteralPath $KeyPath)) {
        try { New-Item -Path $KeyPath -Force -ErrorAction Stop | Out-Null }
        catch { Write-CleanupLog "  $KeyPath key-create FAILED: $($_.Exception.Message)"; return }
    }
    $current = (Get-ItemProperty -LiteralPath $KeyPath -Name $Name -ErrorAction SilentlyContinue).$Name
    if ($null -ne $current -and $current -eq $Value) {
        Write-CleanupLog "  $KeyPath!$Name=$Value already"
        return
    }
    try {
        Set-ItemProperty -LiteralPath $KeyPath -Name $Name -Value $Value -Type $Type -ErrorAction Stop
        Write-CleanupLog "  $KeyPath!$Name CORRECTED: '$current' -> '$Value'"
    } catch {
        Write-CleanupLog "  $KeyPath!$Name correction FAILED: $($_.Exception.Message)"
    }
}

function Set-RegistryValueForAllUsers {
    param([string]$RelativeKeyPath, [string]$Name, [string]$Type, $Value)
    $sids = @((Get-ChildItem 'HKU:\' -ErrorAction SilentlyContinue |
              Where-Object { $_.PSChildName -match '^S-1-5-21-' }).PSChildName)
    $sids += '.DEFAULT'
    foreach ($sid in $sids) {
        Set-RegistryValue -KeyPath "HKU:\$sid\$RelativeKeyPath" -Name $Name -Type $Type -Value $Value
    }
}

function Remove-RegistryKey {
    param([string]$KeyPath)
    if (-not (Test-Path -LiteralPath $KeyPath)) {
        Write-CleanupLog "  $KeyPath absent (no-op)"
        return
    }
    try {
        Remove-Item -LiteralPath $KeyPath -Recurse -Force -ErrorAction Stop
        Write-CleanupLog "  $KeyPath REMOVED"
    } catch {
        Write-CleanupLog "  $KeyPath remove FAILED: $($_.Exception.Message)"
    }
}

function Remove-RegistryKeyForAllUsers {
    param([string]$RelativeKeyPath)
    $sids = @((Get-ChildItem 'HKU:\' -ErrorAction SilentlyContinue |
              Where-Object { $_.PSChildName -match '^S-1-5-21-' }).PSChildName)
    $sids += '.DEFAULT'
    foreach ($sid in $sids) {
        Remove-RegistryKey -KeyPath "HKU:\$sid\$RelativeKeyPath"
    }
}

function Remove-PathIfPresent {
    param([string]$Path, [bool]$Recurse)
    if (-not (Test-Path -LiteralPath $Path)) {
        Write-CleanupLog "  $Path absent (no-op)"
        return
    }
    try {
        if ($Recurse) { Remove-Item -LiteralPath $Path -Recurse -Force -ErrorAction Stop }
        else          { Remove-Item -LiteralPath $Path -Force -ErrorAction Stop }
        Write-CleanupLog "  $Path REMOVED"
    } catch {
        Write-CleanupLog "  $Path remove FAILED: $($_.Exception.Message)"
    }
}

function Remove-PathWithOwnership {
    param([string]$Path, [bool]$Recurse)
    if (-not (Test-Path -LiteralPath $Path)) {
        Write-CleanupLog "  $Path absent (no-op)"
        return
    }
    $adminSid = New-Object System.Security.Principal.SecurityIdentifier 'S-1-5-32-544'
    $admin    = $adminSid.Translate([System.Security.Principal.NTAccount]).Value
    $takeownArgs = @('/f', $Path)
    if ($Recurse) { $takeownArgs += '/r','/d','Y' }
    try {
        & takeown.exe @takeownArgs | Out-Null
        & icacls.exe $Path '/grant' "$admin`:(F)" '/T' '/C' | Out-Null
        if ($Recurse) { Remove-Item -LiteralPath $Path -Recurse -Force -ErrorAction Stop }
        else          { Remove-Item -LiteralPath $Path -Force -ErrorAction Stop }
        Write-CleanupLog "  $Path REMOVED (with takeown)"
    } catch {
        Write-CleanupLog "  $Path takeown-remove FAILED: $($_.Exception.Message)"
    }
}

function Remove-AppxByPackagePrefix {
    param([string]$Prefix)
    $provMatches = @(Get-AppxProvisionedPackage -Online -ErrorAction SilentlyContinue |
                    Where-Object DisplayName -like "$Prefix*")
    if ($provMatches.Count -eq 0) {
        Write-CleanupLog "  appx provisioned '$Prefix*' absent (no-op)"
    } else {
        foreach ($p in $provMatches) {
            try {
                Remove-AppxProvisionedPackage -Online -PackageName $p.PackageName -ErrorAction Stop | Out-Null
                Write-CleanupLog "  appx provisioned $($p.PackageName) REMOVED"
            } catch {
                Write-CleanupLog "  appx provisioned $($p.PackageName) remove FAILED: $($_.Exception.Message)"
            }
        }
    }
    $userMatches = @(Get-AppxPackage -AllUsers -Name "$Prefix*" -ErrorAction SilentlyContinue)
    if ($userMatches.Count -eq 0) {
        Write-CleanupLog "  appx per-user '$Prefix*' absent (no-op)"
    } else {
        foreach ($p in $userMatches) {
            try {
                Remove-AppxPackage -AllUsers -Package $p.PackageFullName -ErrorAction Stop
                Write-CleanupLog "  appx per-user $($p.PackageFullName) REMOVED"
            } catch {
                Write-CleanupLog "  appx per-user $($p.PackageFullName) remove FAILED: $($_.Exception.Message)"
            }
        }
    }
}
'@

$script:footerBlock = @'
Write-CleanupLog '==== tiny11-cleanup done ===='
'@

function Format-PSNamedParams {
    [CmdletBinding()]
    param([Parameter(Mandatory)][System.Collections.IDictionary] $Arguments)
    $parts = foreach ($entry in $Arguments.GetEnumerator()) {
        $value = $entry.Value
        $rendered = if ($value -is [bool]) {
            if ($value) { '$true' } else { '$false' }
        } elseif ($value -is [int] -or $value -is [long]) {
            "$value"
        } elseif ($value -is [byte[]]) {
            $hex = ($value | ForEach-Object { '0x{0:X2}' -f $_ }) -join ','
            "([byte[]]($hex))"
        } elseif ($value -is [array]) {
            $quoted = ($value | ForEach-Object { "'" + ([string]$_ -replace "'", "''") + "'" }) -join ','
            "@($quoted)"
        } else {
            $s = [string]$value
            "'" + ($s -replace "'", "''") + "'"
        }
        "-$($entry.Key) $rendered"
    }
    $parts -join ' '
}

function New-Tiny11PostBootCleanupScript {
    [CmdletBinding()]
    param(
        [Parameter(Mandatory)]            $Catalog,
        [Parameter(Mandatory)][hashtable] $ResolvedSelections
    )
    $sb = [System.Text.StringBuilder]::new()
    [void]$sb.AppendLine($script:headerBlock)
    [void]$sb.AppendLine('')
    [void]$sb.AppendLine($script:helpersBlock)
    [void]$sb.AppendLine('')

    foreach ($item in $Catalog.Items) {
        if (-not $ResolvedSelections.ContainsKey($item.id)) { continue }
        if ($ResolvedSelections[$item.id].EffectiveState -ne 'apply') { continue }

        [void]$sb.AppendLine("# --- Item: $($item.displayName) ($($item.id)) ---")
        foreach ($action in $item.actions) {
            $commands = @(Get-Tiny11ActionOnlineCommand -Action $action)
            foreach ($cmd in $commands) {
                [void]$sb.AppendLine("# $($cmd.Description)")
                $argsRendered = Format-PSNamedParams -Arguments $cmd.Args
                [void]$sb.AppendLine("$($cmd.Kind) $argsRendered")
            }
        }
        [void]$sb.AppendLine('')
    }

    [void]$sb.AppendLine($script:footerBlock)
    $sb.ToString()
}

function New-Tiny11PostBootTaskXml {
    [CmdletBinding()] param()
    throw 'New-Tiny11PostBootTaskXml not yet implemented'
}

function New-Tiny11PostBootSetupCompleteScript {
    [CmdletBinding()] param()
    throw 'New-Tiny11PostBootSetupCompleteScript not yet implemented'
}

function Install-Tiny11PostBootCleanup {
    [CmdletBinding()]
    param(
        [Parameter(Mandatory)][string]    $MountDir,
        [Parameter(Mandatory)]            $Catalog,
        [Parameter(Mandatory)][hashtable] $ResolvedSelections,
        [bool]                            $Enabled = $true
    )
    throw 'Install-Tiny11PostBootCleanup not yet implemented'
}

Export-ModuleMember -Function `
    Format-PSNamedParams, `
    New-Tiny11PostBootCleanupScript, `
    New-Tiny11PostBootTaskXml, `
    New-Tiny11PostBootSetupCompleteScript, `
    Install-Tiny11PostBootCleanup
